// =============================================================================
// SourcedFact + entity schemas — MANUAL
//
// These schemas are the source of truth for v1 entity shapes. They are NOT
// regenerated by orval (which produces `lib/api-zod/src/generated/api.ts` from
// the OpenAPI spec). The generated schemas for the existing search/outreach
// endpoints are still consumed; the new dossier/review-queue/monday-sync/
// battle-card endpoints also flow through this manual file.
//
// Trust contract: every fact a user renders carries a SourcedFact envelope.
// A fact with no resolvable source CANNOT render in a dossier. Hard rule.
// =============================================================================

import { z } from "zod";

// -----------------------------------------------------------------------------
// SourcedFact — the unit of truth
// -----------------------------------------------------------------------------

export const ConfidenceSchema = z.enum(["V", "O", "I"]);
export type Confidence = z.infer<typeof ConfidenceSchema>;

export const VerifiedBySchema = z
  .enum(["rule", "human", "human-import", "doc-import"])
  .nullable();
export type VerifiedBy = z.infer<typeof VerifiedBySchema>;

export const SourcedFactSchema = z.object({
  value: z.string(),
  source_url: z.string().url(),
  retrieved_at: z.string(), // ISO date
  confidence: ConfidenceSchema,
  verified_by: VerifiedBySchema,
  // Cached snapshot for link-rot defense (§11.1). Original URL remains the
  // canonical source; snapshot is the always-works fallback. Weekly link-checker
  // marks live/dead but a dead original does NOT invalidate the fact.
  snapshot_url: z.string().url().optional(),
  // For [I] confidence: the inputs the model was inferred from. Always populated
  // for inferred facts so a human reviewer can audit the chain.
  inference_inputs: z.array(z.string()).optional(),
});
export type SourcedFact = z.infer<typeof SourcedFactSchema>;

// -----------------------------------------------------------------------------
// Source link (v1 — extends the generated SourceLink with `live` and
// `snapshot_url` per §11.1). Renamed to V1SourceLink to avoid collision with
// the generated `SourceLink` from ./generated/types (used by the existing
// scanner endpoints, which are being replaced in v1).
// -----------------------------------------------------------------------------

export const V1SourceLinkSchema = z.object({
  url: z.string().url(),
  title: z.string(),
  publishedDate: z.string().nullable().optional(),
  snippet: z.string().nullable().optional(),
  snapshot_url: z.string().url().optional(),
  live: z.boolean().optional(), // populated by the weekly link-checker
});
export type V1SourceLink = z.infer<typeof V1SourceLinkSchema>;

// -----------------------------------------------------------------------------
// Market — country-level dossier
// -----------------------------------------------------------------------------

export const TierSchema = z.enum(["A", "B", "C", "ANTI"]);
export type Tier = z.infer<typeof TierSchema>;

export const PostureSchema = z.enum([
  "IGNORE",
  "WATCH",
  "WARMUP",
  "ENGAGE",
  "WAR",
]);
export type Posture = z.infer<typeof PostureSchema>;

export const PostureHistoryEntrySchema = z.object({
  posture: PostureSchema,
  ts: z.string(), // ISO datetime
  actor: z.string(), // "engine" | user identifier
  reason: z.string(),
});
export type PostureHistoryEntry = z.infer<typeof PostureHistoryEntrySchema>;

export const FiveQuestionsSchema = z.object({
  know_yourself: SourcedFactSchema,
  know_the_enemy: SourcedFactSchema,
  terrain: SourcedFactSchema,
  timing: SourcedFactSchema,
  win_before_battle: SourcedFactSchema,
});
export type FiveQuestions = z.infer<typeof FiveQuestionsSchema>;

export const MarketSchema = z.object({
  id: z.string(),
  country_iso: z.string().length(2),
  country_name: z.string(),
  tier: TierSchema,
  // v1: posture is HUMAN-SET, guarded by the ≥2-source/1-confirmation change rule
  posture: PostureSchema,
  posture_history: z.array(PostureHistoryEntrySchema),
  verdict: SourcedFactSchema,
  window_opens: z.string().nullable(),
  window_closes: z.string().nullable(),
  five_questions: FiveQuestionsSchema,
  sources: z.array(V1SourceLinkSchema),
  created_at: z.string(),
  updated_at: z.string(),
});
export type Market = z.infer<typeof MarketSchema>;

// -----------------------------------------------------------------------------
// Yard — physical classification yard
// -----------------------------------------------------------------------------

export const YardStatusSchema = z.enum([
  "active",
  "dormant",
  "modernizing",
  "planned",
  "unknown",
]);
export type YardStatus = z.infer<typeof YardStatusSchema>;

export const GeoSchema = z
  .object({
    lat: z.number().nullable(),
    lon: z.number().nullable(),
  })
  .nullable();
export type Geo = z.infer<typeof GeoSchema>;

export const YardSchema = z.object({
  id: z.string(),
  market_id: z.string(),
  name: z.string(),
  // Structural gate (US-1.2): a Yard requires name + country + (coordinates
  // OR named operator). Text fragments CANNOT become Yard entities.
  geo: GeoSchema,
  operator_org_id: z.string().nullable(),
  status: YardStatusSchema,
  brake_tech: SourcedFactSchema.nullable(),
  last_modernized: SourcedFactSchema.nullable(),
  sources: z.array(V1SourceLinkSchema),
  created_at: z.string(),
  updated_at: z.string(),
});
export type Yard = z.infer<typeof YardSchema>;

// -----------------------------------------------------------------------------
// Org — organizations (authority / operator / epc / consultant / etc.)
// -----------------------------------------------------------------------------

export const OrgTypeSchema = z.enum([
  "authority",
  "operator",
  "epc",
  "consultant",
  "financier",
  "competitor",
  "agent",
]);
export type OrgType = z.infer<typeof OrgTypeSchema>;

export const OrgSchema = z.object({
  id: z.string(),
  name: z.string(),
  // ASCII-normalized match key for cross-lingual dedupe (§11.2). e.g.
  // "Zduńska Wola" and "Zdunska Wola" must dedupe to one entity.
  match_key: z.string(),
  type: OrgTypeSchema,
  market_ids: z.array(z.string()),
  monday_item_id: z.string().nullable(),
  innotrans_target: z.boolean(),
  // Per §12.5 GDPR scope rule: criminal/corruption facts attach to Market/Org
  // level only, unnamed. This field captures such facts when relevant.
  risk_facts: z.array(SourcedFactSchema),
  sources: z.array(V1SourceLinkSchema),
  created_at: z.string(),
  updated_at: z.string(),
});
export type Org = z.infer<typeof OrgSchema>;

// -----------------------------------------------------------------------------
// Person
// -----------------------------------------------------------------------------

export const RelationshipStatusSchema = z.enum([
  "none",
  "identified",
  "contacted",
  "active",
  "strong",
]);
export type RelationshipStatus = z.infer<typeof RelationshipStatusSchema>;

export const RoleHistoryEntrySchema = z.object({
  role: z.string(),
  org_id: z.string().nullable(),
  start: z.string().nullable(),
  end: z.string().nullable(),
  source: V1SourceLinkSchema.optional(),
});
export type RoleHistoryEntry = z.infer<typeof RoleHistoryEntrySchema>;

// Per Cassin's correction (Aug 22): for each key contact, the tool surfaces
// what topics this person likely cares about — recent role changes, projects
// they're tied to, public statements, conference appearances. Every entry is
// a SourcedFact. We do NOT generate outreach messages for the contact
// (humans write their own messages) — we tell the operator what the person
// is interested in, so they can write a real one themselves.
export const PersonInterestSchema = z.object({
  // One of: "role_change" · "project" · "public_statement" · "conference" · "publication"
  // "other"
  kind: z.enum([
    "role_change",
    "project",
    "public_statement",
    "conference",
    "publication",
    "other",
  ]),
  // Short human-readable label, e.g. "Spoke at InnoTrans 2025 about retarder safety"
  summary: z.string(),
  // The SourcedFact envelope — every interest is sourced and confidence-tagged
  fact: SourcedFactSchema,
});
export type PersonInterest = z.infer<typeof PersonInterestSchema>;

export const PersonSchema = z.object({
  id: z.string(),
  name: z.string(),
  // Per §12.5 GDPR: business contact data only. No allegations. No criminal/
  // corruption facts. (Those live on Org/Market level, unnamed.)
  org_id: z.string().nullable(),
  role: z.string(),
  role_history: z.array(RoleHistoryEntrySchema),
  // LinkedIn-style profile URL (auto-populated by /api/v1/people/:id/enrich
  // when a data-provider API is configured). See §12.5.5.
  linkedin_url: z.string().url().nullable(),
  // Per Cassin's correction (Aug 22): topics of interest — each is a SourcedFact.
  // Replaces the "generate outreach" feature: humans write messages, the tool
  // tells them what to talk about.
  interests: z.array(PersonInterestSchema).default([]),
  relationship_owner: z.string().nullable(),
  relationship_status: RelationshipStatusSchema,
  // Per US-3.1: machine-parsed from trusted docs (e.g. 92 PLK contacts from
  // xlsx annexes) = doc-import with a pointer to the annex. human-import = a
  // human eyeballed the row. LinkedIn enrichment = "linkedin-enrichment" with
  // the provider API as source_ref.
  import_meta: z
    .object({
      method: z.enum([
        "doc-import",
        "human-import",
        "scrape",
        "linkedin-enrichment",
      ]),
      source_ref: z.string(), // e.g. "OIU_Z1.4.xlsx#sheet=contacts"
      imported_by: z.string().nullable(),
      imported_at: z.string(),
    })
    .nullable(),
  // §12.5.3 retention: persons with no engagement in 24 months → flagged
  // for purge. last_engagement_at drives that flag.
  last_engagement_at: z.string().nullable(),
  monday_item_id: z.string().nullable(),
  sources: z.array(V1SourceLinkSchema),
  created_at: z.string(),
  updated_at: z.string(),
});
export type Person = z.infer<typeof PersonSchema>;

// -----------------------------------------------------------------------------
// Play — sales action item
// -----------------------------------------------------------------------------

export const PlayStatusSchema = z.enum([
  "open",
  "in_progress",
  "done",
  "abandoned",
]);
export type PlayStatus = z.infer<typeof PlayStatusSchema>;

export const PlaySchema = z.object({
  id: z.string(),
  market_id: z.string().nullable(),
  action: z.string(),
  owner: z.string().nullable(),
  due: z.string().nullable(),
  status: PlayStatusSchema,
  origin: z.enum(["engine", "human"]),
  doctrine_ref: z.string().nullable(),
  monday_item_id: z.string().nullable(),
  created_at: z.string(),
});
export type Play = z.infer<typeof PlaySchema>;

// -----------------------------------------------------------------------------
// Correction — the apprentice-loop log (§1.3)
// -----------------------------------------------------------------------------

export const CorrectionActionSchema = z.enum(["confirm", "reject", "edit"]);
export type CorrectionAction = z.infer<typeof CorrectionActionSchema>;

export const CorrectionSchema = z.object({
  id: z.string(),
  fact_id: z.string(),
  fact_kind: z.enum([
    "yard",
    "org",
    "person",
    "market",
    "tender",
    "five_questions",
    "battle_card",
    "source_link",
  ]),
  action: CorrectionActionSchema,
  // The user's corrected value (only populated for action = "edit")
  corrected_value: z.unknown().optional(),
  user: z.string(),
  ts: z.string(),
  // Rejection dedupe key: same source_url + value (content-hash) cannot re-render
  rejection_hash: z.string().optional(),
});
export type Correction = z.infer<typeof CorrectionSchema>;

// -----------------------------------------------------------------------------
// MeetingLog — post-meeting capture (US-4.3, conditional scope in v1)
// -----------------------------------------------------------------------------

export const MeetingLogSchema = z.object({
  id: z.string(),
  org_id: z.string().nullable(),
  person_ids: z.array(z.string()),
  // Per §12.5: this is the operator's own dictation AFTER the meeting, never a
  // recording of counterparts (criminal offence in Germany, §201 StGB).
  raw_note: z.string(),
  audio_ref: z.string().nullable(), // pointer to native voice-memo file
  // All meeting-derived extractions are [I] confidence — they land in the
  // review queue, never auto-render as [V].
  extracted_facts: z.array(z.string()), // fact_ids
  play_id: z.string().nullable(),
  ts: z.string(),
});
export type MeetingLog = z.infer<typeof MeetingLogSchema>;

// -----------------------------------------------------------------------------
// Review queue item — what shows up when a fact can't pass the gate
// -----------------------------------------------------------------------------

export const ReviewQueueItemSchema = z.object({
  id: z.string(),
  // What kind of fact this is
  kind: z.enum([
    "yard",
    "org",
    "person",
    "tender",
    "five_questions",
    "source_link",
  ]),
  // The proposed entity (parsed shape; for editing before promote)
  proposed: z.record(z.string(), z.unknown()),
  // Raw source snippet
  raw_snippet: z.string(),
  source_url: z.string().url(),
  retrieved_at: z.string(),
  market_id: z.string().nullable(),
  // Queue age: anything older than 14 days auto-archives (recoverable)
  ts: z.string(),
});
export type ReviewQueueItem = z.infer<typeof ReviewQueueItemSchema>;

// -----------------------------------------------------------------------------
// Battle card — pre-rendered offline target briefing (US-4.1, US-4.2)
// -----------------------------------------------------------------------------

export const BattleCardSchema = z.object({
  // canonical org id, or special "*" for the InnoTrans-wide list
  org_id: z.string(),
  // 1. Who they are
  who_they_are: z.string(),
  // 2. Why they matter to DECEL (doctrine line — written by Cassin, §11.10)
  why_matters: z.string(),
  // 3. Known people + roles
  known_people: z.array(
    z.object({
      person_id: z.string(),
      role: z.string(),
      relationship_status: RelationshipStatusSchema,
    }),
  ),
  // 4. Our relationship status (overall)
  relationship_status: RelationshipStatusSchema,
  // 5. Three suggested questions (Cassin-authored)
  suggested_questions: z.array(z.string()).length(3),
  // 6. Trap to avoid (Cassin-authored)
  trap_to_avoid: z.string(),
  // 7. Sources
  sources: z.array(V1SourceLinkSchema),
  // Card kind:
  //   - "relationship" — buyer/authority card with known people
  //   - "recon"        — competitor card; observer questions only
  //   - "watchlist_plus" — hand-curated, no auto extraction (W36 scope cut)
  kind: z.enum(["relationship", "recon", "watchlist_plus"]),
  // For "recon" cards: what to observe instead of relationship content
  recon_what_to_observe: z.array(z.string()).optional(),
  // Doctrine version tracking (§11.11)
  doctrine_version: z.number().int().nonnegative(),
  doctrine_updated_at: z.string(),
  doctrine_updated_by: z.string(),
});
export type BattleCard = z.infer<typeof BattleCardSchema>;

// -----------------------------------------------------------------------------
// Doctrine version (cheap edit history for curated content)
// -----------------------------------------------------------------------------

export const DoctrineRevisionSchema = z.object({
  content_kind: z.enum(["five_questions", "battle_card", "play"]),
  content_id: z.string(),
  version: z.number().int().nonnegative(),
  diff: z.string(), // human-readable diff or JSON diff blob
  author: z.string(),
  ts: z.string(),
});
export type DoctrineRevision = z.infer<typeof DoctrineRevisionSchema>;
